- hosts: all
  become: yes
  tasks:
  - name: reset tous les noeuds
    command: "kubeadm reset -f "
  - name: supprimer les fichiers sur master
    file: 
     path: "{{ item }}"
     state: absent
    loop:
     - /etc/kubernetes/
     - /var/lib/etcd/
     - /var/lib/kubelet/
     - /home/vagrant/.kube"
    when: "'master' in inventory_hostname"
  - name: Vérifier le reset
    command: "for i in `ps aux | grep kube | awk {'print $2'}` ; do kill -9 $i; done"
  - name: supprimer containerd
    apt:
     name: containerd
     state: absent
     purge: true
