apiVersion: v1
kind: Namespace
metadata:
  name: demoapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  labels:
    app: demoapp
  namespace: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: brahimhamdi/demoapp:latest
---          
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  labels:
    app: demoapp
  namespace: demoapp
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: demoapp
